package ingsis.components.statement

enum class StatementType {
    DECLARATION,
    ASSIGNATION,
    COMPOUND_ASSIGNATION,
    FUNCTION,
    PRINT_LINE,
    IF,
    ELSE,
    COMPOUND_ASSIGNATION_READ_INPUT,
    ASSIGNATION_READ_INPUT,
    COMPOUND_ASSIGNATION_READ_ENV,
    ASSIGNATION_READ_ENV,
}
