/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("PrintScript.kotlin-application-conventions")
}

dependencies {
    api(project(":cli"))
    implementation("com.github.ajalt.clikt:clikt:4.3.0")
}

application {
    // Define the main class for the application.
    mainClass.set("PrintScript.app.AppKt")
}
