/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("PrintScript.kotlin-library-conventions")
}

dependencies {
    api(project(":utils"))
    api(project(":components"))
    api(project(":sca"))
}
