name: Build and Test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deployment

    steps:
      - uses: actions/checkout@v4.1.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: corretto
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Tests
        run: ./gradlew test
        env:
          GITHUB_AUTHOR: ${{ secrets.AUTHOR }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}