name: Build and Publish

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: corretto
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish package
        run: ./gradlew publish
        env: 
          GITHUB_AUTHOR: ${{secrets.AUTHOR}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
